// Root ESLint flat config.
//
// Each app under apps/* owns its own eslint.config.mjs (generated by its
// framework CLI) which takes precedence when linting is run from within
// that app's directory. This root config is used for everything else:
// packages/* (shared libraries) and tests/ (cross-cutting test suites).
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import eslintConfigPrettier from 'eslint-config-prettier';
import globals from 'globals';

export default tseslint.config(
  {
    ignores: ['**/dist/**', '**/build/**', '**/.next/**', '**/.expo/**', 'apps/**', 'prisma/generated/**'],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    languageOptions: {
      globals: {
        ...globals.node,
      },
    },
    rules: {
      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
    },
  },
  eslintConfigPrettier,
);
